name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run:
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build the docker image
      run: cd FinalProj;
           docker build -t grocer_model:latest .
    - name: Docker Push
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker tag grocer_model:latest ${{secrets.DOCKER_USER}}/class705.603/grocer_model:latest;
           docker login -u $DOCKER_USER -p $DOCKER_PASSWORD;
           docker push ${{secrets.DOCKER_USER}}/class705.603/grocer_model:latest
